services:

##########################################
##
## project chimba / trading automation
##
##########################################

    project-chimba-trading-automation:

        container_name: project-chimba-trading-automation
        
        image: softwareshinobi/project-chimba-trading-automation

        build: 

            context: .

            dockerfile: Dockerfile
    
        restart: unless-stopped

        ports:

            - 7777:7777

        expose:

            - 8888

        environment:

            VIRTUAL_HOST: apis.projectchimba.softwareshinobi.digital

            LETSENCRYPT_HOST: apis.projectchimba.softwareshinobi.digital

    project-chimba-trading-web:

        container_name: project-chimba-trading-web

        image: softwareshinobi/project-chimba-trading-web

        build: 

            context: web

            dockerfile: Dockerfile

        ports:

            - 7770:80

        environment:

            VIRTUAL_HOST: projectchimba.softwareshinobi.digital

            LETSENCRYPT_HOST: projectchimba.softwareshinobi.digital

    project-chimba-trading-docs:

        container_name: project-chimba-trading-docs

        image: softwareshinobi/project-chimba-trading-docs

        build: 

            context: docs

            dockerfile: Dockerfile

        ports:

            - 7772:80

        environment:

            VIRTUAL_HOST: docs.projectchimba.softwareshinobi.digital

            LETSENCRYPT_HOST: docs.projectchimba.softwareshinobi.digital

    project-chimba-trading-watch:

        container_name: project-chimba-trading-watch

        image: softwareshinobi/project-chimba-trading-watch

        build: 

            context: watch

            dockerfile: Dockerfile

        ports:

            - 7773:80

        environment:

            VIRTUAL_HOST: watch.projectchimba.softwareshinobi.digital

            LETSENCRYPT_HOST: watch.projectchimba.softwareshinobi.digital
