services:

##########################################
##
## network infrastructure
##
##########################################

    project-chimba-trading-proxy:

        container_name: project-chimba-trading-proxy

        image: nginxproxy/nginx-proxy

        restart: unless-stopped

        ports:

            - 80:80

            - 443:443

        volumes:

            - /var/run/docker.sock:/tmp/docker.sock:ro

            - /var/docker/nginx/html:/usr/share/nginx/html

            - /var/docker/nginx/certs:/etc/nginx/certs

            - /var/docker/nginx/vhost:/etc/nginx/vhost.d

        logging:

            options:

                max-size: "10m"

                max-file: "3"

    project-chimba-trading-letsencrypt:

        container_name: project-chimba-trading-letsencrypt

        image: jrcs/letsencrypt-nginx-proxy-companion

        restart: unless-stopped

        volumes_from:

            - project-chimba-trading-proxy

        volumes:

            - /var/run/docker.sock:/var/run/docker.sock

            - /var/docker/nginx/acme:/etc/acme.sh

        environment:

            DEFAULT_EMAIL: the.software.shinobi@gmail.com

##########################################
##
## projectchimba / trading automation
##
##########################################

    project-chimba-trading-automation:

        container_name: project-chimba-trading-automation
        
        image: softwareshinobi/project-chimba-trading-automation

        build: 

            context: .

            dockerfile: Dockerfile
    
        restart: unless-stopped

        ports:

            - "8888:8888"

        environment:

            VIRTUAL_HOST: apis.projectchimba.softwareshinobi.digital

            LETSENCRYPT_HOST: apis.projectchimba.softwareshinobi.digital

    project-chimba-trading-web:

        container_name: project-chimba-trading-web

        image: softwareshinobi/project-chimba-trading-web

        build: 

            context: web

            dockerfile: Dockerfile

        ports:

            - 8880:80

        environment:

            VIRTUAL_HOST: projectchimba.softwareshinobi.digital

            LETSENCRYPT_HOST: projectchimba.softwareshinobi.digital

    project-chimba-trading-docs:

        container_name: project-chimba-trading-docs

        image: softwareshinobi/project-chimba-trading-docs

        build: 

            context: docs

            dockerfile: Dockerfile

        ports:

            - 8882:80

        environment:

            VIRTUAL_HOST: docs.projectchimba.softwareshinobi.digital

            LETSENCRYPT_HOST: docs.projectchimba.softwareshinobi.digital
            