services:

    web:

        container_name: web

        image: nginx:latest

        user: "1000"

        volumes:
        
            - ${PWD}:/usr/share/nginx/html/           
         
        ports:

            - 55555:80
